export const GET_TENANT_DUES_REQUEST = "GET_TENANT_DUES_REQUEST";
export const GET_TENANT_DUES_SUCCESS = "GET_TENANT_DUES_SUCCESS";
export const GET_TENANT_DUES_FAILURE = "GET_TENANT_DUES_FAILURE";

export const GET_TENANT_DUES_BY_ID_REQUEST = "GET_TENANT_DUES_BY_ID_REQUEST";
export const GET_TENANT_DUES_BY_ID_SUCCESS = "GET_TENANT_DUES_BY_ID_SUCCESS";
export const GET_TENANT_DUES_BY_ID_FAILURE = "GET_TENANT_DUES_BY_ID_FAILURE";

export const GET_LANDLORD_DUES_REQUEST = "GET_LANDLORD_DUES_REQUEST";
export const GET_LANDLORD_DUES_SUCCESS = "GET_LANDLORD_DUES_SUCCESS";
export const GET_LANDLORD_DUES_FAILURE = "GET_LANDLORD_DUES_FAILURE";

export const GET_DUE_BY_ID_REQUEST = "GET_DUE_BY_ID_REQUEST";
export const GET_DUE_BY_ID_SUCCESS = "GET_DUE_BY_ID_SUCCESS";
export const GET_DUE_BY_ID_FAILURE = "GET_DUE_BY_ID_FAILURE";
