export const CREATE_RENT_PAYMENT_REQUEST = "CREATE_RENT_PAYMENT_REQUEST";
export const CREATE_RENT_PAYMENT_SUCCESS = "CREATE_RENT_PAYMENT_SUCCESS";
export const CREATE_RENT_PAYMENT_FAIL = "CREATE_RENT_PAYMENT_FAIL";

export const VERIFY_RENT_PAYMENT_REQUEST = "VERIFY_RENT_PAYMENT_REQUEST";
export const VERIFY_RENT_PAYMENT_SUCCESS = "VERIFY_RENT_PAYMENT_SUCCESS";
export const VERIFY_RENT_PAYMENT_FAIL = "VERIFY_RENT_PAYMENT_FAIL";

export const GET_PAYMENTS_REQUEST = "GET_PAYMENTS_REQUEST";
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_FAIL = "GET_PAYMENTS_FAIL";

export const RESET_RENT_PAYMENT = "RESET_RENT_PAYMENT";