export const CREATE_MAINTENANCE_REQUEST = "CREATE_MAINTENANCE_REQUEST";
export const CREATE_MAINTENANCE_SUCCESS = "CREATE_MAINTENANCE_SUCCESS";
export const CREATE_MAINTENANCE_FAILURE = "CREATE_MAINTENANCE_FAILURE";

export const GET_TENANT_MAINTENANCE_REQUEST = "GET_TENANT_MAINTENANCE_REQUEST";
export const GET_TENANT_MAINTENANCE_SUCCESS = "GET_TENANT_MAINTENANCE_SUCCESS";
export const GET_TENANT_MAINTENANCE_FAILURE = "GET_TENANT_MAINTENANCE_FAILURE";

export const GET_TENANTID_MAINTENANCE_REQUEST = "GET_TENANTID_MAINTENANCE_REQUEST";
export const GET_TENANTID_MAINTENANCE_SUCCESS = "GET_TENANTID_MAINTENANCE_SUCCESS";
export const GET_TENANTID_MAINTENANCE_FAILURE = "GET_TENANTID_MAINTENANCE_FAILURE";

export const GET_LANDLORD_MAINTENANCE_REQUEST = "GET_LANDLORD_MAINTENANCE_REQUEST";
export const GET_LANDLORD_MAINTENANCE_SUCCESS = "GET_LANDLORD_MAINTENANCE_SUCCESS";
export const GET_LANDLORD_MAINTENANCE_FAILURE = "GET_LANDLORD_MAINTENANCE_FAILURE";

export const UPDATE_MAINTENANCE_STATUS_REQUEST = "UPDATE_MAINTENANCE_STATUS_REQUEST";
export const UPDATE_MAINTENANCE_STATUS_SUCCESS = "UPDATE_MAINTENANCE_STATUS_SUCCESS";
export const UPDATE_MAINTENANCE_STATUS_FAILURE = "UPDATE_MAINTENANCE_STATUS_FAILURE";
