export const  REGISTER_REQUEST = 'REGISTER_REQUEST';
export const  REGISTER_SUCCESS = 'RESISTER_SUCCESS';
export const  REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';

export const GET_MY_TENANTS_REQUEST = 'GET_MY_TENANTS_REQUEST';
export const GET_MY_TENANTS_SUCCESS = 'GET_MY_TENANTS_SUCCESS';
export const GET_MY_TENANTS_FAILURE = 'GET_MY_TENANTS_FAILURE';

export const GET_MY_LANDLORD_REQUEST = 'GET_MY_LANDLORD_REQUEST';
export const GET_MY_LANDLORD_SUCCESS = 'GET_MY_LANDLORD_SUCCESS';
export const GET_MY_LANDLORD_FAILURE = 'GET_MY_LANDLORD_FAILURE';

export const UPDATE_SUBSCRIPTION_REQUEST = "UPDATE_SUBSCRIPTION_REQUEST";
export const UPDATE_SUBSCRIPTION_SUCCESS = "UPDATE_SUBSCRIPTION_SUCCESS";
export const UPDATE_SUBSCRIPTION_FAILURE = "UPDATE_SUBSCRIPTION_FAILURE";

export const UPDATE_PROFILE_IMAGE_REQUEST = "UPDATE_PROFILE_IMAGE_REQUEST";
export const UPDATE_PROFILE_IMAGE_SUCCESS = "UPDATE_PROFILE_IMAGE_SUCCESS";
export const UPDATE_PROFILE_IMAGE_FAILURE = "UPDATE_PROFILE_IMAGE_FAILURE";


export const LOGOUT = 'LOGOUT';