
export const GET_TENANT_HISTORY_REQUEST = "GET_TENANT_HISTORY_REQUEST";
export const GET_TENANT_HISTORY_SUCCESS = "GET_TENANT_HISTORY_SUCCESS";
export const GET_TENANT_HISTORY_FAILURE = "GET_TENANT_HISTORY_FAILURE";

export const DELETE_TENANT_HISTORY_REQUEST = "DELETE_TENANT_HISTORY_REQUEST";
export const DELETE_TENANT_HISTORY_SUCCESS = "DELETE_TENANT_HISTORY_SUCCESS";
export const DELETE_TENANT_HISTORY_FAILURE = "DELETE_TENANT_HISTORY_FAILURE";
