// CREATE
export const CREATE_SUBPROPERTY_REQUEST = "CREATE_SUBPROPERTY_REQUEST";
export const CREATE_SUBPROPERTY_SUCCESS = "CREATE_SUBPROPERTY_SUCCESS";
export const CREATE_SUBPROPERTY_FAIL = "CREATE_SUBPROPERTY_FAIL";

export const GET_SUBPROPERTIES_BY_PROPERTY_REQUEST =
  "GET_SUBPROPERTIES_BY_PROPERTY_REQUEST";
export const GET_SUBPROPERTIES_BY_PROPERTY_SUCCESS =
  "GET_SUBPROPERTIES_BY_PROPERTY_SUCCESS";
export const GET_SUBPROPERTIES_BY_PROPERTY_FAIL =
  "GET_SUBPROPERTIES_BY_PROPERTY_FAIL";

export const GET_SUBPROPERTIES_BY_LANDLORD_REQUEST =
  "GET_SUBPROPERTIES_BY_LANDLORD_REQUEST";
export const GET_SUBPROPERTIES_BY_LANDLORD_SUCCESS =
  "GET_SUBPROPERTIES_BY_LANDLORD_SUCCESS";
export const GET_SUBPROPERTIES_BY_LANDLORD_FAIL =
  "GET_SUBPROPERTIES_BY_LANDLORD_FAIL";

export const DELETE_SUBPROPERTY_REQUEST = "DELETE_SUBPROPERTY_REQUEST";
export const DELETE_SUBPROPERTY_SUCCESS = "DELETE_SUBPROPERTY_SUCCESS";
export const DELETE_SUBPROPERTY_FAIL = "DELETE_SUBPROPERTY_FAIL";

export const VACATE_SUBPROPERTY_REQUEST = "VACATE_SUBPROPERTY_REQUEST";
export const VACATE_SUBPROPERTY_SUCCESS = "VACATE_SUBPROPERTY_SUCCESS";
export const VACATE_SUBPROPERTY_FAIL = "VACATE_SUBPROPERTY_FAIL";

export const GET_SUBPROPERTY_BY_CURRENT_TENANT_REQUEST =
  "GET_SUBPROPERTY_BY_CURRENT_TENANT_REQUEST";
export const GET_SUBPROPERTY_BY_CURRENT_TENANT_SUCCESS =
  "GET_SUBPROPERTY_BY_CURRENT_TENANT_SUCCESS";
export const GET_SUBPROPERTY_BY_CURRENT_TENANT_FAIL =
  "GET_SUBPROPERTY_BY_CURRENT_TENANT_FAIL";

export const RESET_SUBPROPERTY_STATE = "RESET_SUBPROPERTY_STATE";
