export const INVITE_TENANT_REQUEST = "INVITE_TENANT_REQUEST";
export const INVITE_TENANT_SUCCESS = "INVITE_TENANT_SUCCESS";
export const INVITE_TENANT_FAIL = "INVITE_TENANT_FAIL";

export const ACCEPT_INVITE_REQUEST = "ACCEPT_INVITE_REQUEST";
export const ACCEPT_INVITE_SUCCESS = "ACCEPT_INVITE_SUCCESS";
export const ACCEPT_INVITE_FAIL = "ACCEPT_INVITE_FAIL";

export const GET_INVITATIONS_REQUEST = "GET_INVITATIONS_REQUEST";
export const GET_INVITATIONS_SUCCESS = "GET_INVITATIONS_SUCCESS";
export const GET_INVITATIONS_FAIL = "GET_INVITATIONS_FAIL";

export const INVITE_EXISTING_REQUEST = "INVITE_EXISTING_REQUEST";
export const INVITE_EXISTING_SUCCESS = "INVITE_EXISTING_SUCCESS";
export const INVITE_EXISTING_FAIL = "INVITE_EXISTING_FAIL";

export const ACCEPT_EXISTING_REQUEST = "ACCEPT_EXISTING_REQUEST";
export const ACCEPT_EXISTING_SUCCESS = "ACCEPT_EXISTING_SUCCESS";
export const ACCEPT_EXISTING_FAIL = "ACCEPT_EXISTING_FAIL";

export const RESET_INVITATION_STATE = "RESET_INVITATION_STATE";
